name: Build bcm2709 6.1
on: [push]

jobs:
    build:
        name: Prepare and build bcm2709 images
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Update and install feeds
              run: |
                ./scripts/feeds update -a
                ./scripts/feeds install -a

            - name: Generate config for bcm2709 6.1
              run: |
                cp .github/workflows/config.buildinfo .config
                make defconfig

            - name: Download package sources
              run: make download V=s

            - name: Build tools
              run: |
                make tools/install -j$(nproc) V=s || \
                make tools/install V=s

            - name: Build toolchain
              run: |
                make toolchain/install -j$(nproc) V=s || \
                make toolchain/install V=s

            - name: Build target images
              run: |
                make -j$(nproc) V=s 'IGNORE_ERRORS=n m' || \
                make V=s 'IGNORE_ERRORS=n m'

            - name: TAR output
              run: tar -cvf bcm27xx-images.tar bin/targets/bcm27xx/bcm2709

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: bcm27xx-images
                path: bcm27xx-images.tar

    release:
          name: Make a release
          runs-on: ubuntu-latest
          needs: build

          steps:
            - name: Download the image artifacts
              uses: actions/download-artifact@v3
              with:
                name: bcm27xx-images

            - name: Extract the image artifacts
              run: tar xf bcm27xx-images.tar

            - name: Create a release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: true
                title: "BCM2709 v6.1 Images"
                automatic_release_tag: "bcm2709-6.1"
                files: bin/targets/bcm27xx/bcm2709/*
